[tool.isort]
# profile = "black"
skip = [".gitignore", ".dockerignore"]
extend_skip = [".md", ".json"]
force_single_line = true
lines_after_imports = 2
# include_trailing_comma = true
# [tool.black]
# line-length = 120
# skip-string-normalization = false


# RUFF
#   - rules: https://beta.ruff.rs/docs/rules/
#   - settings: https://beta.ruff.rs/docs/settings/ 
[tool.ruff]
line-length = 140
[tool.ruff.isort]
force-single-line = true
# force-sort-within-section = true
[tool.ruff.mccabe]
max-complexity = 10
[tool.ruff.pydocstyle]
convention = "numpy"
[tool.ruff.flake8-annotations]
allow-star-arg-any = true
ignore-fully-untyped = true